version: "3.9"
services:
  app:
      build:
        context: .
        dockerfile: Dockerfile
      env_file:
        - .env
      ports:
        - ${PORT}:${PORT}
      depends_on:
        - db
      command: pnpm run start
  db:
    image: postgres:alpine
    container_name: pg_db
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    
volumes:
  pg_data: